### PR TITLE
include crash reporting as dependency

### PR DESCRIPTION
**Pull request by Melvine**
# Description 
Include crash reporting as dependency.

## Links
Add links to github/jira issues, design documents and other relevant resources (e.g. previous discussions, platform/tool documentation etc.)

# Checklist
- [ ] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [ ] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by NemoOudeis — CHANGES_REQUESTED** [review]
This is not enough to integrate the 2 features.
Here are some concerns with this PR:

* You didn't fill the PR template
* just adding the runtime dependency does not enable clients to use the crash tracking feature. Without uploading the mapping the runtime is pretty much useless.
* hardcoding the runtime dependency means we will need to update the code of both plugins (this and the crash one) whenever the runtime changes -> that's a code smell
* Your approach breaks a bunch of tests
* My suggestion from the start was to add a dependency onto a self contained crash-reporting plugin to this plugin (in `plugin/build.gradle` and then do 
```groovy
class PerfPlugin implements Plugin<Project> { 	 
  @Override
  void apply(Project project) {
    new CrashReportingPlugin().apply(project);
    // below this performance tracking stays as is
  }
}
```

- [ ] fill the PR template
- [ ] add a dependency onto the crash plugin and apply it to the project in `PerfPlugin#apply`.
- [ ] come up with plan for integration testing on circle ci

about the last point: to avoid that problem with the perf tracking runtime we add the following to integration test build files:
```groovy
configurations.all {
    exclude group: 'com.rakuten.tech.mobile.perf', module: 'performance-tracking'
}
```
you can probably add something similar for crash tracking

**Comment by Melvine** [comment]
> My suggestion from the start was to add a dependency onto a self contained crash-reporting plugin to this plugin (in plugin/build.gradle and then do ... 

Could you help clarify on this step? 
From what I see, the rak artifactory is not included in `Plugin/build.gradle`. Would it be better to set up in the buildscript block in the root `build.gradle` with the repository and the crash report plugin dependency there? Although even when I did that with gradle sync'd, I could not get  `new CrashReportingPlugin()` to be found.

Also, I tried running `./gradlew check` even without my changes and it has failed checks. Wonder if I am missing something there?

**Comment by NemoOudeis** [comment]
> Could you help clarify on this step?

`plugin/build.gradle` should have a `compile` dependency onto the crash reporting plugin.
that way you have `CrashReportingPlugin` on the classpath when `PerfPlugin` runs.

> Also, I tried running ./gradlew check even without my changes and it has failed checks. Wonder if I am missing something there?

What is it that's failing? If you provide a log I can try to help.
I just checked out `master` and `check` runs for me 😕
Recently there's an issue with one of the gradle test kit integration tests on circle CI that we cannot reproduce locally - maybe you have the same issue and can help to solve it 😃

**Comment by Melvine** [comment]
Hmm yea strange how it didn't work out for me right away. Near the end of the file are the failures noticeable. Here is the log: 
[gradlew-check.txt](https://github.com/rakutentech/android-perftracking/files/1818489/gradlew-check.txt)

TL:DR
``` 
com.rakuten.tech.mobile.perf.PerfPluginExtensionIntegrationSpec > plugin should use real rewriter for debug build according to extension FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at PerfPluginExtensionIntegrationSpec.groovy:27

com.rakuten.tech.mobile.perf.PerfPluginIntegrationSpec > plugin should use dummy rewriter for debug build FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at PerfPluginIntegrationSpec.groovy:38

com.rakuten.tech.mobile.perf.PerfPluginIntegrationSpec > plugin should use real rewriter for release build FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at PerfPluginIntegrationSpec.groovy:51

com.rakuten.tech.mobile.perf.PerfPluginIntegrationSpec > plugin should add transformation tasks FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at PerfPluginIntegrationSpec.groovy:27
:Plugin:test FAILED
:Plugin:generateCoberturaReport
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Report time: 23ms
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Report time: 19ms
:Plugin:performCoverageCheck SKIPPED
20 actionable tasks: 5 executed, 15 up-to-date
```

**Pull request closed without merging**
